project:
  type: website

website:
  title: "Text as Data: Language Models, AI, and NLP Techniques for Historical and Literary Texts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weeks
        menu:
          - href: week-01-introduction.qmd
            text: "Week 01: Introduction"
          - href: week-02-basics.qmd
            text: "Week 02: Basics"
          - href: week-03-dictionaries.qmd
            text: "Week 03: Dictionaries"
