project:
  type: website

format:
  html:
    theme: sandstone

website:
  title: "Text as Data: Language Models, AI, and NLP Techniques for Historical and Literary Texts"

  navbar:
    title: "Text as Data"
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: docked
    search: true
    contents:
      - section: "Course"
        contents:
          - index.qmd

      - section: "Weeks"
        contents:
          - href: week-01-introduction.qmd
            text: "Week 01: Introduction"
          - href: week-02-basics.qmd
            text: "Week 02: Basics"
          - href: week-03-dictionaries.qmd
            text: "Week 03: Dictionaries"
          - href: week-04-representation.qmd
            text: "Week 04: Text Representation (1)"
          - href: week-05-representation.qmd
            text: "Week 05: Text Representation (2)"
          - href: week-06-cooccurrence.qmd
            text: "Week 06: Co-occurrence & PMI"
          - href: week-07-word2vec.qmd
            text: "Week 07: Word2Vec and LDA introduction"
          - href: week-08-09-word2vec.qmd
            text: "Week 07: Weeks 08 & 9: Weak Supervision & Supervised Text Classification in Python"