project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: lesson-01-tokenization.qmd
            text: Lesson 01: Tokenization
          - href: lesson-02-bigrams.qmd
            text: Lesson 02: Bigrams
          - href: lesson-03-tfidf.qmd
            text: Lesson 03: TFâ€“IDF
