project:
  type: website

website:
  title: "Text as Data: Language Models, AI, and NLP Techniques for Historical and Literary Texts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lessons
        menu:
          - href: lesson-01-tokenization.qmd
            text: "Lesson 01: Tokenization"
          - href: lesson-02-bigrams.qmd
            text: "Lesson 02: Bigrams"
          - href: lesson-03-regex.qmd
            text: "Lesson 03: regex"
